services:
  pihole:
    container_name: pihole
    image: cilindrox/pihole:1.0.1
    build:
      context: .
      dockerfile: Dockerfile
    hostname: pihole-backup
    domainname: home.local
    ports:
      - 53:53/tcp
      - 53:53/udp
    expose:
      - 80
    environment:
      ADMIN_EMAIL: cilindrox+pi@gmail.com
      PIHOLE_DNS_: '127.0.0.1#5335'
      TZ: 'America/Montevideo'
      SKIPGRAVITYONBOOT: 1
      FTLCONF_LOCAL_IPV4: 192.168.1.10
      ServerIP: 192.168.1.10
      WEBPASSWORD: ${WEBPASSWORD:?Please configure WEBPASSWORD in the .env file}
    volumes:
      - './unbound-pihole.conf:/etc/unbound/unbound.conf.d/pi-hole.conf:ro'
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    stop_grace_period: 2m
    networks:
      - pihole

networks:
  pihole:
    driver: bridge
