version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: cilindrox/pihole:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    hostname: pihole-backup
    domainname: home.local
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    expose:
      - 80
    environment:
      ADMIN_EMAIL: cilindrox+pi@gmail.com
      PIHOLE_DNS_: '127.0.0.1#5335'
      TZ: 'America/Montevideo'
      SKIPGRAVITYONBOOT: 1
      WEBPASSWORD: ${WEBPASSWORD:?Please configure WEBPASSWORD in the .env file}
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    stop_grace_period: 2m
    networks:
      - pihole

networks:
  pihole:
    driver: bridge
